### ISSUE TITLE
Inference script

### ISSUE THREAD

**Issue by RameshArvind** [conceptofmind/PaLM#1]
I think the inference script needs a flag for setting dtype (fp16 / bf16), else the script breaks when it triggers flash attention.

Also does torch.compile work for inference? The hidet repo currently says that dynamic shape isn't supported. I didn't notice any speed-ups enabling or disabling your torch.compile step in your script.

**Comment by conceptofmind** [comment]
Hi @RameshArvind,

I will add a dtype flag to handle that case.

The blog on Hidet was relatively new and I added it largely as a test to explore the use of `torch.compile()`. I did notice that it did not improve inference but I personally wanted to examine whether it could make a difference so I left it for the time being. It is very possible that it will not have any impact.

Thank you,

Enrico Shippole

**Comment by RameshArvind** [comment]
Ah I see, thanks for clarifying! Will close the issue.
