### ISSUE TITLE
When will the fused version of stable adamw coms out?

### ISSUE THREAD

**Issue by Life-0-1** [conceptofmind/PaLM#10]
Exactly, this is not a issue. 

In my experiments, stable adamw gives a much better stability on loss curve. In order to training faster, I want to use a fused version, but it really stumped me because I don't have any knowledge in CUDA programming. 

I tried to modify the fused_adam.cu, but its computations are all about element-wise, and its unknown to implementing a tensor-wise RMS.

**Comment by conceptofmind** [comment]
I spoke to the author of Stable Adam W and he stated that there would be a minimal performance boost from using the fused kernel. He is also not able to release the fused version until a bug is fixed in the Triton repository.

**Comment by Life-0-1** [comment]
I see, thanks.
