### ISSUE TITLE
Error when running in google colab and kaggle

### ISSUE THREAD

**Issue by huypham1103** [conceptofmind/PaLM#11]
Hi, I am trying to run your code at the usage part. Unfortunately, Both environments raise this error. Have a nice day!
![image](https://github.com/conceptofmind/PaLM/assets/129708251/338a2fa1-cb36-4671-819a-41da8ab79958)

**Comment by conceptofmind** [comment]
You need to download the pytorch model file and specify the correct path to it in Colab. Such as `./path/to/my/model/palm_410m_8k_V0.pt`.

Or try to using torch hub to automatically download the file: `model = torch.hub.load("conceptofmind/PaLM", "palm_410m_8k_v0").cuda()`

**Comment by huypham1103** [comment]
Thank you! Have a nice day!
