### ISSUE TITLE
ERROR: Could not build wheels for nvtx, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by qiuqingpo** [conceptofmind/PaLM#4]
**hello, when i install the requirement "hidet", use the command "pip3 install hidet",it was  failed, the error detail is** 

> Building wheels for collected packages: nvtx
>   Building wheel for nvtx (pyproject.toml) ... error
>   error: subprocess-exited-with-error
> 
>   × Building wheel for nvtx (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [30 lines of output]
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build\lib.win-amd64-cpython-310
>       creating build\lib.win-amd64-cpython-310\nvtx
>       copying nvtx\colors.py -> build\lib.win-amd64-cpython-310\nvtx
>       copying nvtx\nvtx.py -> build\lib.win-amd64-cpython-310\nvtx
>       copying nvtx\__init__.py -> build\lib.win-amd64-cpython-310\nvtx
>       copying nvtx\__main__.py -> build\lib.win-amd64-cpython-310\nvtx
>       creating build\lib.win-amd64-cpython-310\nvtx\utils
>       copying nvtx\utils\cached.py -> build\lib.win-amd64-cpython-310\nvtx\utils
>       copying nvtx\utils\__init__.py -> build\lib.win-amd64-cpython-310\nvtx\utils
>       creating build\lib.win-amd64-cpython-310\nvtx\_lib
>       copying nvtx\_lib\__init__.py -> build\lib.win-amd64-cpython-310\nvtx\_lib
>       creating build\lib.win-amd64-cpython-310\nvtx\_lib\tests
>       copying nvtx\_lib\tests\__init__.py -> build\lib.win-amd64-cpython-310\nvtx\_lib\tests
>       copying nvtx\_lib\lib.pxd -> build\lib.win-amd64-cpython-310\nvtx\_lib
>       copying nvtx\_lib\profiler.pxd -> build\lib.win-amd64-cpython-310\nvtx\_lib
>       copying nvtx\_lib\__init__.pxd -> build\lib.win-amd64-cpython-310\nvtx\_lib
>       running build_ext
>       building 'nvtx._lib.lib' extension
>       creating build\temp.win-amd64-cpython-310
>       creating build\temp.win-amd64-cpython-310\Release
>       creating build\temp.win-amd64-cpython-310\Release\nvtx
>       creating build\temp.win-amd64-cpython-310\Release\nvtx\_lib
>       "d:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.31.30818\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\qiuqingpo\AppData\Local\Programs\Python\Python310 -IC:\Users\qiuqingpo\AppData\Local\Programs\Python\Python310\include -IC:\Users\qiuqingpo\AppData\Local\Programs\Python\Python310\Include "-Id:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.31.30818\ATLMFC\include" "-Id:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.31.30818\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-ID:\Windows Kits\10\include\10.0.19041.0\ucrt" "-ID:\Windows Kits\10\\include\10.0.19041.0\\shared" "-ID:\Windows Kits\10\\include\10.0.19041.0\\um" "-ID:\Windows Kits\10\\include\10.0.19041.0\\winrt" "-ID:\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" /Tcnvtx\_lib\lib.c /Fobuild\temp.win-amd64-cpython-310\Release\nvtx\_lib\lib.obj
>       lib.c
>       nvtx\_lib\lib.c(766): fatal error C1083: 无法打开包括文件: “nvtx3/nvToolsExt.h”: No such file or directory
>       error: command 'd:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\VC\\Tools\\MSVC\\14.31.30818\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for nvtx
> Failed to build nvtx
> ERROR: Could not build wheels for nvtx, which is required to install pyproject.toml-based projects
> 
> [notice] A new release of pip available: 22.2.2 -> 23.1.2
> [notice] To update, run: python.exe -m pip install --upgrade pip
> 

**my computer is intel cup and display adapter, can i use it? or have other suggestions ?thank you very much**

**Comment by conceptofmind** [comment]
Try installing only:
```
torch>=2.0.0
palm-rlhf-pytorch
transformers
datasets
tokenizers
```

For CPU try something like:
```python
import torch
from transformers import AutoTokenizer
from palm_rlhf_pytorch import PaLM

def generate(prompt, seq_len=128, temperature=0.8, filter_thres=0.9):
    device = torch.device("cpu")

    model = PaLM(
        num_tokens=50304, dim=1024, depth=24, dim_head=128, heads=8, flash_attn=False, qk_rmsnorm = False,
    ).to(device).eval()

    checkpoint = torch.load('./palm_410m_8k_v0.pt', map_location=device)
    model.load_state_dict(checkpoint)

    tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neox-20b")

    encoded_text = tokenizer(prompt, return_tensors="pt")

    output_tensor = model.generate(
        seq_len=seq_len,
        prompt=encoded_text["input_ids"].to(device),
        temperature=temperature,
        filter_thres=filter_thres,
        pad_value=0.0,
        eos_token=tokenizer.eos_token_id,
        return_seq_without_prompt=False,
        use_tqdm=True,
    )

    decoded_output = tokenizer.batch_decode(output_tensor, skip_special_tokens=True)

    return decoded_output[0]

generate()
    ```

**Comment by qiuqingpo** [comment]
> 
thank you very much! I will try it later and tell you result.

**Comment by qiuqingpo** [comment]
OK, the codes can run, but it still have errors ,do I have to download all files from the url "https://huggingface.co/EleutherAI/gpt-neox-20b/tree/main", I only download two ".safetensors" files

 
> PS D:\My\2023\PaLM> python inferencecpu.py "My dog is very cute" --seq_len 256 --temperature 0.8 --filter_thres 0.9 --model "palm_1b_8k_v0.pt"
> Traceback (most recent call last):
>   File "D:\My\2023\PaLM\inferencecpu.py", line 64, in <module>
>     generated_text = generate()
>   File "D:\My\2023\PaLM\inferencecpu.py", line 41, in generate
>     model.load_state_dict(checkpoint)
>   File "C:\Users\qiuqingpo\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for PaLM:
>         Missing key(s) in state_dict: "layers.16.fn.norm.gamma", "layers.16.fn.norm.beta", "layers.16.fn.rotary_emb.inv_freq", "layers.16.fn.rotary_emb.scale", "layers.16.fn.fused_attn_ff_proj.weight", "layers.16.fn.attn_out.weight", "layers.16.fn.ff_out.2.weight", "layers.17.fn.norm.gamma", "layers.17.fn.norm.beta", "layers.17.fn.rotary_emb.inv_freq", "layers.17.fn.rotary_emb.scale", "layers.17.fn.fused_attn_ff_proj.weight", "layers.17.fn.attn_out.weight", "layers.17.fn.ff_out.2.weight", "layers.18.fn.norm.gamma", "layers.18.fn.norm.beta", "layers.18.fn.rotary_emb.inv_freq", "layers.18.fn.rotary_emb.scale", "layers.18.fn.fused_attn_ff_proj.weight", "layers.18.fn.attn_out.weight", "layers.18.fn.ff_out.2.weight", "layers.19.fn.norm.gamma", "layers.19.fn.norm.beta", "layers.19.fn.rotary_emb.inv_freq", "layers.19.fn.rotary_emb.scale", "layers.19.fn.fused_attn_ff_proj.weight", "layers.19.fn.attn_out.weight", "layers.19.fn.ff_out.2.weight", "layers.20.fn.norm.gamma", "layers.20.fn.norm.beta", "layers.20.fn.rotary_emb.inv_freq", "layers.20.fn.rotary_emb.scale", "layers.20.fn.fused_attn_ff_proj.weight", "layers.20.fn.attn_out.weight", "layers.20.fn.ff_out.2.weight", "layers.21.fn.norm.gamma", "layers.21.fn.norm.beta", "layers.21.fn.rotary_emb.inv_freq", "layers.21.fn.rotary_emb.scale", "layers.21.fn.fused_attn_ff_proj.weight", "layers.21.fn.attn_out.weight", "layers.21.fn.ff_out.2.weight", "layers.22.fn.norm.gamma", "layers.22.fn.norm.beta", "layers.22.fn.rotary_emb.inv_freq", "layers.22.fn.rotary_emb.scale", "layers.22.fn.fused_attn_ff_proj.weight", "layers.22.fn.attn_out.weight", "layers.22.fn.ff_out.2.weight", "layers.23.fn.norm.gamma", "layers.23.fn.norm.beta", "layers.23.fn.rotary_emb.inv_freq", "layers.23.fn.rotary_emb.scale", "layers.23.fn.fused_attn_ff_proj.weight", "layers.23.fn.attn_out.weight", "layers.23.fn.ff_out.2.weight".
>         size mismatch for token_emb.weight: copying a param with shape torch.Size([50304, 2048]) from checkpoint, the shape in current model is torch.Size([50304, 1024]).
>         size mismatch for layers.0.fn.norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.0.fn.norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.0.fn.fused_attn_ff_proj.weight: copying a param with shape torch.Size([17664, 2048]) from checkpoint, the shape in current model is torch.Size([9472, 1024]).
>         size mismatch for layers.0.fn.attn_out.weight: copying a param with shape torch.Size([2048, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
>         size mismatch for layers.0.fn.ff_out.2.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
>         size mismatch for layers.1.fn.norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.1.fn.norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.1.fn.fused_attn_ff_proj.weight: copying a param with shape torch.Size([17664, 2048]) from checkpoint, the shape in current model is torch.Size([9472, 1024]).
>         size mismatch for layers.1.fn.attn_out.weight: copying a param with shape torch.Size([2048, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
>         size mismatch for layers.1.fn.ff_out.2.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
>         size mismatch for layers.2.fn.norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.2.fn.norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.2.fn.fused_attn_ff_proj.weight: copying a param with shape torch.Size([17664, 2048]) from checkpoint, the shape in current model is torch.Size([9472, 1024]).
>         size mismatch for layers.2.fn.attn_out.weight: copying a param with shape torch.Size([2048, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
>         size mismatch for layers.2.fn.ff_out.2.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
>         size mismatch for layers.3.fn.norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.3.fn.norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.3.fn.fused_attn_ff_proj.weight: copying a param with shape torch.Size([17664, 2048]) from checkpoint, the shape in current model is torch.Size([9472, 1024]).
>         size mismatch for layers.3.fn.attn_out.weight: copying a param with shape torch.Size([2048, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
>         size mismatch for layers.3.fn.ff_out.2.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
>         size mismatch for layers.4.fn.norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.4.fn.norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.4.fn.fused_attn_ff_proj.weight: copying a param with shape torch.Size([17664, 2048]) from checkpoint, the shape in current model is torch.Size([9472, 1024]).
>         size mismatch for layers.4.fn.attn_out.weight: copying a param with shape torch.Size([2048, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
>         size mismatch for layers.4.fn.ff_out.2.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
>         size mismatch for layers.5.fn.norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.5.fn.norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.5.fn.fused_attn_ff_proj.weight: copying a param with shape torch.Size([17664, 2048]) from checkpoint, the shape in current model is torch.Size([9472, 1024]).
>         size mismatch for layers.5.fn.attn_out.weight: copying a param with shape torch.Size([2048, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
>         size mismatch for layers.5.fn.ff_out.2.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
>         size mismatch for layers.6.fn.norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.6.fn.norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.6.fn.fused_attn_ff_proj.weight: copying a param with shape torch.Size([17664, 2048]) from checkpoint, the shape in current model is torch.Size([9472, 1024]).
>         size mismatch for layers.6.fn.attn_out.weight: copying a param with shape torch.Size([2048, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
>         size mismatch for layers.6.fn.ff_out.2.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
>         size mismatch for layers.7.fn.norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.7.fn.norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.7.fn.fused_attn_ff_proj.weight: copying a param with shape torch.Size([17664, 2048]) from checkpoint, the shape in current model is torch.Size([9472, 1024]).
>         size mismatch for layers.7.fn.attn_out.weight: copying a param with shape torch.Size([2048, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
>         size mismatch for layers.7.fn.ff_out.2.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
>         size mismatch for layers.8.fn.norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.8.fn.norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.8.fn.fused_attn_ff_proj.weight: copying a param with shape torch.Size([17664, 2048]) from checkpoint, the shape in current model is torch.Size([9472, 1024]).
>         size mismatch for layers.8.fn.attn_out.weight: copying a param with shape torch.Size([2048, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
>         size mismatch for layers.8.fn.ff_out.2.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
>         size mismatch for layers.9.fn.norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.9.fn.norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.9.fn.fused_attn_ff_proj.weight: copying a param with shape torch.Size([17664, 2048]) from checkpoint, the shape in current model is torch.Size([9472, 1024]).
>         size mismatch for layers.9.fn.attn_out.weight: copying a param with shape torch.Size([2048, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
>         size mismatch for layers.9.fn.ff_out.2.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
>         size mismatch for layers.10.fn.norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.10.fn.norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.10.fn.fused_attn_ff_proj.weight: copying a param with shape torch.Size([17664, 2048]) from checkpoint, the shape in current model is torch.Size([9472, 1024]).
>         size mismatch for layers.10.fn.attn_out.weight: copying a param with shape torch.Size([2048, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
>         size mismatch for layers.10.fn.ff_out.2.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
>         size mismatch for layers.11.fn.norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.11.fn.norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.11.fn.fused_attn_ff_proj.weight: copying a param with shape torch.Size([17664, 2048]) from checkpoint, the shape in current model is torch.Size([9472, 1024]).
>         size mismatch for layers.11.fn.attn_out.weight: copying a param with shape torch.Size([2048, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
>         size mismatch for layers.11.fn.ff_out.2.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
>         size mismatch for layers.12.fn.norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.12.fn.norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.12.fn.fused_attn_ff_proj.weight: copying a param with shape torch.Size([17664, 2048]) from checkpoint, the shape in current model is torch.Size([9472, 1024]).
>         size mismatch for layers.12.fn.attn_out.weight: copying a param with shape torch.Size([2048, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
>         size mismatch for layers.12.fn.ff_out.2.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
>         size mismatch for layers.13.fn.norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.13.fn.norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.13.fn.fused_attn_ff_proj.weight: copying a param with shape torch.Size([17664, 2048]) from checkpoint, the shape in current model is torch.Size([9472, 1024]).
>         size mismatch for layers.13.fn.attn_out.weight: copying a param with shape torch.Size([2048, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
>         size mismatch for layers.13.fn.ff_out.2.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
>         size mismatch for layers.14.fn.norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.14.fn.norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.14.fn.fused_attn_ff_proj.weight: copying a param with shape torch.Size([17664, 2048]) from checkpoint, the shape in current model is torch.Size([9472, 1024]).
>         size mismatch for layers.14.fn.attn_out.weight: copying a param with shape torch.Size([2048, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
>         size mismatch for layers.14.fn.ff_out.2.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
>         size mismatch for layers.15.fn.norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.15.fn.norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for layers.15.fn.fused_attn_ff_proj.weight: copying a param with shape torch.Size([17664, 2048]) from checkpoint, the shape in current model is torch.Size([9472, 1024]).
>         size mismatch for layers.15.fn.attn_out.weight: copying a param with shape torch.Size([2048, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
>         size mismatch for layers.15.fn.ff_out.2.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
>         size mismatch for norm.gamma: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for norm.beta: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
>         size mismatch for to_logits.weight: copying a param with shape torch.Size([50304, 2048]) from checkpoint, the shape in current model is torch.Size([50304, 1024]).
>

**Comment by qiuqingpo** [comment]
the code line " tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neox-20b")" still error,the details is below:

> PS D:\My\2023\PaLM> python inferencecpu.py "My dog is very cute" --seq_len 256 --temperature 0.8 --filter_thres 0.9 --model "palm_1b_8k_v0.pt"
> Traceback (most recent call last):
>   File "D:\My\2023\PaLM\inferencecpu.py", line 63, in <module>
>     generated_text = generate()
>   File "D:\My\2023\PaLM\inferencecpu.py", line 42, in generate
>     tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neox-20b")
>   File "C:\Users\qiuqingpo\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 711, in from_pretrained
>     return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
>   File "C:\Users\qiuqingpo\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\tokenization_utils_base.py", line 1812, in from_pretrained
>     return cls._from_pretrained(
>   File "C:\Users\qiuqingpo\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\tokenization_utils_base.py", line 1975, in _from_pretrained
>     tokenizer = cls(*init_inputs, **init_kwargs)
>   File "C:\Users\qiuqingpo\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\gpt_neox\tokenization_gpt_neox_fast.py", line 113, in __init__
>     super().__init__(
>   File "C:\Users\qiuqingpo\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\tokenization_utils_fast.py", line 120, in __init__
>     raise ValueError(
> ValueError: Couldn't instantiate the backend tokenizer from one of:
> (1) a `tokenizers` library serialization file,
> (2) a slow tokenizer instance to convert or
> (3) an equivalent slow tokenizer class to instantiate and convert.
> You need to have sentencepiece installed to convert a slow tokenizer to a fast one.

my code is below:

`import torch
from transformers import AutoTokenizer
from palm_rlhf_pytorch import PaLM
import argparse

def generate():

    parser = argparse.ArgumentParser(description="Generate text using PaLM model")
    parser.add_argument("prompt", type=str, help="Text prompt to generate text")
    parser.add_argument(
        "--seq_len", type=int, default=256, help="Sequence length for generated text"
    )
    parser.add_argument(
        "--temperature", type=float, default=0.8, help="Sampling temperature"
    )
    parser.add_argument(
        "--filter_thres", type=float, default=0.9, help="Filter threshold for sampling"
    )
    parser.add_argument(
        "--model",
        type=str,
        default="palm_1b_8k_v0",
        help="Model to use for generation",
    )

    parser.add_argument(
        "--dtype",
        type=str,
        default="fp32",
        help="Data type for the model: 'bf16', or 'fp32'",
    )

    args = parser.parse_args()
    device = torch.device("cpu")

    model = PaLM(
        num_tokens=50304, dim=2048, depth=16, dim_head=128, heads=8, flash_attn=False, qk_rmsnorm = False,
    ).to(device).eval()
    checkpoint = torch.load(args.model, map_location=device)
    model.load_state_dict(checkpoint)

    tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neox-20b")

    encoded_text = tokenizer(args.prompt, return_tensors="pt")

    output_tensor = model.generate(
        seq_len=args.seq_len,
        prompt=encoded_text["input_ids"].to(device),
        temperature=args.temperature,
        filter_thres=args.filter_thres,
        pad_value=0.0,
        eos_token=tokenizer.eos_token_id,
        return_seq_without_prompt=False,
        use_tqdm=True,
    )

    decoded_output = tokenizer.batch_decode(output_tensor, skip_special_tokens=True)

    return decoded_output[0]


if __name__ == "__main__":
    generated_text = generate()
    for text in generated_text:
        print(f"{text}")
`

**Comment by conceptofmind** [comment]
Can you try adding a config.json file similar to: https://huggingface.co/EleutherAI/gpt-neox-20b/blob/main/config.json

**Comment by qiuqingpo** [comment]
> Can you try adding all of the relevant .json files similar to: https://huggingface.co/EleutherAI/gpt-neox-20b/blob/main/config.json https://huggingface.co/EleutherAI/gpt-neox-20b/blob/main/tokenizer_config.json
> 
> This seems like an issue related to Huggingface. I am not sure why when you use the tokenizer it is not downloading all of right configs. I will have to look further into it.
> 
> Can try installing `sentencepiece` as well?

thank you very much, I am success! i download the files  "config.json,tokenizer_config.json,tokenizer.json" in the file dir "EleutherAI\gpt-neox-20b", and i get the results,thank you very much!
