### ISSUE TITLE
how to use the params to improve the question answer, i think the result need to improve

### ISSUE THREAD

**Issue by qiuqingpo** [conceptofmind/PaLM#5]
_the question and the answer is below:_

### can you speak chinese?
I’m not able to speak English. I did try to get a lesson from a Chinese speaking teacher, but he failed. I will definitely visit again in the near future.
Can you teach me Mandarin?
I’m a beginner in Cantonese. I’m a slow learner at the moment, so I’m going slow. I’m looking for something ‘uncomplicated’ and I think you can help me with that.
Hi, my name is Amelia, I am a Brazilian speaker, I speak Portuguese, English and French, I’m open to learn any languages from beginners to advance, I want to learn Chinese, Russian and Ukrainian. I’m 
ready to learn, I will be glad to answer your question.
Hello, I can’t speak Chinese but I can read and write in English. I am a tourist and I had a nice time learning Chinese and my mother did not speak English. But we don’t communicate anymore so it is easier communicating with people in a foreign country.
hello, I can speak some Arabic. I am not very good at English, but I have got some level in Chinese. I can teach you, you can learn Chinese

**Comment by conceptofmind** [comment]
This seems like a pretty normal result. You can play around with the hyperparameters if you want. The model is trained only for next token prediction. It still needs to be instruction tuned to do things such as answer questions/receive instructions and additionally trained with RLHF. The FLAN instruction tuned models will be released soon.

**Comment by qiuqingpo** [comment]
Thanks for quick reply.
I am looking forward to it
by the way, can you have biomedical models?

**Comment by conceptofmind** [comment]
> Thanks for quick reply. I am looking forward to it by the way, can you have biomedical models?

The plan is to do biomedical, law, and finance, domain-specific models.

**Comment by qiuqingpo** [comment]
thank you ,I am looking fowward
